### ISSUE TITLE
Fails to resolve 'fortune' state if translation hasn't been chosen

### ISSUE THREAD

**Issue by sdoxsee** [jdubois/generator-jhipster-fortune#1]
scripts/app/fortune/fortune.js

```
            resolve: {
                mainTranslatePartialLoader: ['$translate', '$translatePartialLoader', function ($translate,$translatePartialLoader) {
                    $translatePartialLoader.addPart('fortune');
                    return $translate.refresh();
                }]
            }
```

will fail because there is no $tranlsate service (if translation isn't enabled)

**Comment by pascalgrimaud** [comment]
This commit has resolved your issue : https://github.com/jdubois/generator-jhipster-fortune/commit/673c3019405080819cfbd2f04bd9e06ad9b84e94

You'll have to wait the next release (v0.0.2) to fix it

**Comment by sdoxsee** [comment]
My bad. I didn't research it carefully enough. Thanks. Closing

**Comment by pascalgrimaud** [comment]
No problem. If you look this project fortune, maybe you'll begin a module.
Let us know your repo module (with twitter for example) ;)
