### ISSUE TITLE
Module seems broken

### ISSUE THREAD

**Issue by bastienmichaux** [jdubois/generator-jhipster-fortune#3]
**Edit** : this was an authorization error on my node modules. I'm a complete idiot. This issue can be closed. I leave the original text in case someone has the same problem. 

---

This module seems broken. I installed the module with NPM, created a new JHipster app with this module selected from the Marketplace, then called `yo jhipster-fortune`. I got the following error :

`Error! The JHipster Fortune module only works with SQL databases`

Index.js makes this check :

```js
if (jhipsterVar.databaseType !== 'sql') {
  this.log(chalk.red('Error!') + ' The JHipster Fortune module only works with SQL databases');
  process.exit(1);
}
```

Quite confusing since this is my app info :

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.altissia",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.0",
    "baseName": "test1",
    "packageName": "com.altissia",
    "packageFolder": "com/altissia",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "40aaf25b2901607499fa77c42c4457130477c0ba",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

This is because `jhipsterVar` has no `databaseType` property at this moment. 

I hardcoded `jhipsterVar` to pass this error, then got :

```
? Please write your own fortune cookie Use OKLM razor in case of competing hypotheses.
Composing JHipster configuration with module fortune
Reading the JHipster project configuration for your module
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: jhipsterFunc.addJavaScriptToIndex is not a function
    at child.writing (/usr/lib/node_modules/generator-jhipster-fortune/generators/app/index.js:74:18)
    at /usr/lib/node_modules/generator-jhipster-fortune/node_modules/yeoman-generator/lib/base.js:430:16
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

I don't know if the module is broken or if I did something wrong. You can suggest me a fix since I want to learn how to work with JHipster modules.

**Edit** : I ran `sudo yo jhipster-fortune` and got the prompt right this time. But I still have the `TypeError: jhipsterFunc.addJavaScriptToIndex is not a function` error. It may be an authorization missing on my device. I'll test again with more authorizations.

**Edit** : Ok, this was an authorization error on my device.

**Comment by jdubois** [comment]
OK, I'm closing this as you say it's your fault, but I haven't updated that module since a very long time, so it can be broken!

**Comment by 8652** [comment]
@bastienmichaux sorry to bother you, I have the same question now and don't know how to deal with it. Could you please tell me how to solve it? thank you very much.
